# Generated by Django 3.2.19 on 2025-04-04 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20201230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_end_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='expected end date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='start date'),
        ),
    ]
