# Generated by Django 3.2.19 on 2025-10-27 15:03

from django.db import migrations

def set_completion_percent_if_closed(apps, schema_editor):
    TaskStatus = apps.get_model('projects', 'TaskStatus')
    TaskStatus.objects.filter(is_closed=True).update(completion_percent=100)

def unset_completion_percent_if_closed(apps, schema_editor):
    TaskStatus = apps.get_model('projects', 'TaskStatus')
    TaskStatus.objects.filter(is_closed=True).update(completion_percent=0)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_taskstatus_completion_percent'),
    ]



    operations = [
        migrations.RunPython(
            set_completion_percent_if_closed,
            reverse_code=unset_completion_percent_if_closed
        ),
    ]
