# Generated by Django 3.2.19 on 2025-11-27 18:58

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_alter_project_public_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(
                blank=True, 
                default=None, 
                help_text='Completion percentage of the task (0 to 100)', 
                null=True, 
                validators=[
                    django.core.validators.MinValueValidator(0), 
                    django.core.validators.MaxValueValidator(100)
                ], 
                verbose_name='completion percent'),
        ),
    ]