# Generated by Django 3.2.19 on 2025-05-15 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0006_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AddField(
            model_name='epic',
            name='expected_completion_date',
            field=models.DateField(default=datetime.date(2020, 1, 2), verbose_name='expected completion date'),
        ),
        migrations.AddField(
            model_name='epic',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='start date'),
        ),
    ]
