# Generated by Django 3.2.19 on 2025-07-04 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0007_auto_20250515_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentual de conclusão baseado nas user stories (0 a 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='completion percent'),
        ),
    ]
