# Generated by Django 3.2.19 on 2026-04-04 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_populate_completion_percent'),
        ('epics', '0011_auto_20250731_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='percentage_impact',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percentage impact'),
        ),
        migrations.AddField(
            model_name='epic',
            name='schedulable',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='is schedulable'),
        ),
        migrations.CreateModel(
            name='EpicMonthlySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='year month')),
                ('completion_percent_done', models.IntegerField(default=0, verbose_name='completion percent done')),
                ('percentage_impact', models.IntegerField(default=0, verbose_name='percentage impact')),
                ('schedulable', models.BooleanField(blank=True, null=True, verbose_name='schedulable')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is closed')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, verbose_name='snapshot date')),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='epics.epic', verbose_name='epic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_monthly_snapshots', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'epic monthly snapshot',
                'verbose_name_plural': 'epic monthly snapshots',
                'ordering': ['year_month'],
            },
        ),
        migrations.AddIndex(
            model_name='epicmonthlysnapshot',
            index=models.Index(fields=['project', 'year_month'], name='epics_epicm_project_b68bff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='epicmonthlysnapshot',
            unique_together={('epic', 'year_month')},
        ),
    ]
