# Generated by Django 3.2.19 on 2025-07-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0022_userstory_completion_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='completion_percent',
        ),
    ]
