# Generated by Django 3.2.19 on 2025-07-04 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0023_add_userstory_completion_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentual de conclusão baseado nas tasks (0 a 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='completion percent'),
        ),
    ]
