# Generated by Django 3.2.19 on 2025-07-18 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0025_rename_and_add_completion_percent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='completion_percent_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='completion_percent_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentual de conclusão baseado nas tasks (0 a 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='completion percent progress'),
        ),
    ]
