# Generated by Django 3.2.19 on 2026-10-01 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taiga.news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0034_alter_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to=taiga.news.models.get_slide_image_file_path, verbose_name='image')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.IntegerField(blank=True, default=10, verbose_name='order')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='modified date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_slides_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_slides_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
                'ordering': ('order', 'id'),
            },
        ),
    ]
