# Generated by Django 3.2.19 on 2025-06-23 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Completion percentage of the task (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='completion percent'),
        ),
    ]
