# Generated by Django 3.2.19 on 2025-07-31 13:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20250718_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_percent_done',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Completion percentage marked as done (0.00 to 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='completion percent done'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_percent_progress',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Completion percentage of the task (0.00 to 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='completion percent progress'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('completion_percent_progress__gte', 0), ('completion_percent_progress__lte', 100)), name='task_percent_progress_0_100'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('completion_percent_done__gte', 0), ('completion_percent_done__lte', 100)), name='task_percent_done_0_100'),
        ),
    ]
