# Generated by Django 3.2.19 on 2025-10-15 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0068_auto_20250404_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified date')),
                ('finished_date', models.DateTimeField(blank=True, null=True, verbose_name='finished date')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='is active')),
                ('status', models.CharField(choices=[('RE', 'Related'), ('DP', 'Depends'), ('BK', 'Blocked'), ('DU', 'Duplicated')], default='RE', max_length=2, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('card_ref', models.BigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='reference')),
                ('dependent_card_ref', models.BigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='dependent reference')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_card_relations', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('finished_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_card_relations', to=settings.AUTH_USER_MODEL, verbose_name='finished by')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_card_relations', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relations_by', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'card relation',
                'verbose_name_plural': 'card relations',
                'ordering': ['project', 'card_ref', 'status'],
            },
        ),
    ]
