# Generated by Django 3.2.19 on 2025-11-09 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0009_auto_20200615_0811'),
        ('card_relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardrelation',
            options={'verbose_name': 'Card Relation', 'verbose_name_plural': 'Card Relations'},
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='relation_type',
            field=models.CharField(choices=[('RT', 'RELATED TO'), ('BK', 'BLOCKS'), ('BKBY', 'BLOCKED BY'), ('DPON', 'DEPENDS ON'), ('DPME', 'DEPENDS ME'), ('DUBY', 'DUPLICATED BY'), ('DUFROM', 'DUPLICATED_FROM'), ('DWT', 'DISCOVERED WHILE TESTING')], default='RT', max_length=10),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='source_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_as_source', to='issues.issue', verbose_name='source_card'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='target_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_as_target', to='issues.issue', verbose_name='target_card'),
        ),
        migrations.AlterField(
            model_name='cardrelation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_relations_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='cardrelation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='cardrelation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_relations_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified_by'),
        ),
        migrations.AlterField(
            model_name='cardrelation',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_date'),
        ),
        migrations.AlterUniqueTogether(
            name='cardrelation',
            unique_together={('source_card', 'target_card', 'relation_type')},
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='card_ref',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='dependent_card_ref',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='finished_by',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='status',
        ),
    ]
