# Generated by Django 3.2.19 on 2025-11-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_alter_project_public_permissions'),
        ('card_relations', '0002_auto_20251109_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_relations', to='projects.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='source_id',
            field=models.PositiveIntegerField(null=True, verbose_name='source id'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='source_type',
            field=models.CharField(choices=[('issue', 'Issue'), ('userstory', 'User story'), ('task', 'Task'), ('epic', 'Epic')], max_length=20, null=True, verbose_name='source_type'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='target_id',
            field=models.PositiveIntegerField(null=True, verbose_name='target id'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='target_type',
            field=models.CharField(choices=[('issue', 'Issue'), ('userstory', 'User story'), ('task', 'Task'), ('epic', 'Epic')], max_length=20, null=True, verbose_name='target type'),
        ),
        migrations.AlterUniqueTogether(
            name='cardrelation',
            unique_together={('project', 'source_type', 'source_id', 'target_type', 'target_id', 'relation_type')},
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='source_card',
        ),
        migrations.RemoveField(
            model_name='cardrelation',
            name='target_card',
        ),
    ]
