# Generated by Django 3.2.19 on 2025-11-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_relations', '0003_auto_20251116_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='cardrelation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
    ]
