# Generated by Django 3.2.19 on 2025-11-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0071_alter_project_public_permissions'),
        ('card_relations', '0004_auto_20251116_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_relations_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved_by'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolved_date'),
        ),
        migrations.AlterUniqueTogether(
            name='cardrelation',
            unique_together={('project', 'source_type', 'source_id', 'target_type', 'target_id', 'relation_type', 'is_active')},
        ),
    ]
