# Generated by Django 3.2.19 on 2025-11-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_relations', '0005_auto_20251117_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelation',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='modified_date'),
        ),
    ]
