# Generated by Django 3.2.19 on 2025-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_relations', '0006_alter_cardrelation_modified_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardrelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cardrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'source_type', 'source_id', 'target_type', 'target_id', 'relation_type'), name='unique_active_card_relation'),
        ),
    ]
