# Generated by Django 3.2.19 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_relations', '0007_auto_20251118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelation',
            name='relation_type',
            field=models.CharField(choices=[('RT', 'RELATED TO'), ('BK', 'BLOCKS'), ('BKBY', 'BLOCKED BY'), ('DPON', 'DEPENDS ON'), ('DPME', 'DEPENDS ME'), ('DUBY', 'DUPLICATED BY'), ('DUFROM', 'DUPLICATED_FROM'), ('DWT', 'DISCOVERED WHILE TESTING'), ('LTDWT', 'LED TO DISCOVERED DURING TESTING')], default='RT', max_length=10),
        ),
    ]
